apiVersion: v1
kind: Service
metadata:
  name: insights-on-prem
spec:
  selector:
    app: insights-on-prem
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
